BarnetPages(Services)/BarnetPages/Areas/Admin/Models/ErrorViewModel.cs
using System;

namespace BarnetPages.Areas
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BarnetPages(Services)/BarnetPages/Models/Client.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models
{
    public class Client
    {
        [Key]
        public int Id { get; set; }

        public string Content { get; set; }

        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [MaxLength(50)]
        public string Name { get; set; }

        public DateTime CretedDate { get; set; }

    }
}

BarnetPages(Services)/BarnetPages/Models/ErrorViewModel.cs
using System;

namespace BarnetPages.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BarnetPages(Services)/BarnetPages/Models/Service.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models
{
    public class Service
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(250)]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [MaxLength(250)]
        public string Title { get; set; }

        [MaxLength(250)]
        public string SupTitle { get; set; }

        [MaxLength(50)]
        public string Icon { get; set; }

        public DateTime CretedDate { get; set; }

    }
}

BarnetPages(Services)/BarnetPages/Models/Setting.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models
{
    public class Setting
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(250)]
        public string Logo { get; set; }
        [NotMapped]
        public IFormFile LogoFile { get; set; }

        [MaxLength(50)]
        public string Phone { get; set; }

        [MaxLength(50)]
        public string Email { get; set; }

        [MaxLength(250)]
        public string Adress { get; set; }

        [MaxLength(1000)]
        public string Content { get; set; }
    }
}

BarnetPages(Services)/BarnetPages/Models/Social.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models
{
    public class Social
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(50)]
        public string Icon { get; set; }

        [MaxLength(250)]
        public string Link { get; set; }
    }
}

BarnetPages(Services)/BarnetPages/Models/Subscribe.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models
{
    public class Subscribe
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(50)]
        public string Email { get; set; }

        public DateTime CretedDate { get; set; }
    }
}

BarnetPages(Services)/BarnetPages/Models/ViewModels/VmService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Models.ViewModels
{
    public class VmService
    {
        public List<Service> Services { get; set; }
        public List<Client> Clients { get; set; }
        public Setting Setting { get; set; }
        public List<Social> Socials { get; set; }
        public Subscribe Subscribe { get; set; }
    }
}

BarnetPages(Services)/BarnetPages/Areas/Admin/Controllers/ServiceController.cs
using BarnetPages.Data;
using BarnetPages.Models;
using BarnetPages.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ServiceController : Controller
    {
        private readonly AppDbContext _context;
        public ServiceController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            VmService model = new VmService();
            model.Services = _context.Services.ToList();


            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Service model)
        {
            if (ModelState.IsValid)
            {
                _context.Services.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }
        public IActionResult Update(int id)
        {
            return View(_context.Services.Find(id));
        }

        [HttpPost]
        public IActionResult Update(Service model)
        {
            if (ModelState.IsValid)
            {
                _context.Services.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }
        public IActionResult Delete(int id)
        {
            Service service = _context.Services.Find(id);
            _context.Services.Remove(service);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BarnetPages(Services)/BarnetPages/Controllers/HomeController.cs
using BarnetPages.Data;
using BarnetPages.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

BarnetPages(Services)/BarnetPages/Controllers/ServiceController.cs
using BarnetPages.Data;
using BarnetPages.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BarnetPages.Controllers
{
    public class ServiceController : Controller
    {
        private readonly AppDbContext _context;

        public ServiceController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            VmService model = new VmService();
            model.Services = _context.Services.ToList();
            model.Clients = _context.Clients.ToList();
            model.Setting = _context.Settings.FirstOrDefault();
            model.Socials = _context.Socials.ToList();
            model.Subscribe = _context.Subscribes.FirstOrDefault();

            return View(model);
        }
    }
}

BarnetPages(Services)/BarnetPages/Areas/Admin/Views/Service/Create.cshtml
@model Service
@{ ViewData["Title"] = "Create";
                Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }


<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form asp-area="Admin" asp-controller="Service" asp-action="Create" method="post">
                <div class="form-group">
                    <label asp-for="@Model.Image">Image</label>
                    <input class="form-control" asp-for="@Model.Image">
                    <span asp-validation-for="@Model.Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Title">Title</label>
                    <input class="form-control" asp-for="@Model.Title">
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="@Model.SupTitle">SupTitle</label>
                    <input class="form-control" asp-for="@Model.SupTitle">
                    <span asp-validation-for="@Model.SupTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Icon">Icon</label>
                    <input class="form-control" asp-for="@Model.Icon">
                    <span asp-validation-for="@Model.Icon" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.CretedDate">CreatedDate</label>
                    <input class="form-control" asp-for="@Model.CretedDate">
                    <span asp-validation-for="@Model.CretedDate" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Create</button>
                <button type="submit" class="btn btn-dark" asp-controller="Blog" asp-action="Index">Back to List</button>

            </form>
        </div>
    </div>
</div>

BarnetPages(Services)/BarnetPages/Areas/Admin/Views/Service/Index.cshtml
@model VmService

@{ ViewData["Title"] = "Index";
                Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }



<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary mb-3" asp-area="Admin" asp-controller="Service" asp-action="Create">Create</a>
        </div>
        <div class="col-lg-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">SubTitle</th>
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col">CreatedDate</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0;
                        foreach (var item in Model.Services)
                        {
                            i++;
            <tr>
                <th scope="row">@i</th>
                <td>@item.Image</td>
                <td>@item.Title</td>
                <td>@item.SupTitle</td>
                <td>@item.Icon</td>
                <td>@item.CretedDate</td>
                <td>
                    <a class="btn btn-success" asp-area="Admin" asp-controller="Service" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Service" asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure?')">Delete</a>
                </td>
            </tr> } }
                </tbody>
            </table>
        </div>
    </div>
</div>

BarnetPages(Services)/BarnetPages/Areas/Admin/Views/Service/Update.cshtml
@model Service
@{ ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; }


<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <form asp-area="Admin" asp-controller="Service" asp-action="Update" method="post">
                <div class="form-group">
                    <label asp-for="@Model.Image">Image</label>
                    <input class="form-control" asp-for="@Model.Image">
                    <span asp-validation-for="@Model.Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Title">Title</label>
                    <input class="form-control" asp-for="@Model.Title">
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="@Model.SupTitle">SupTitle</label>
                    <input class="form-control" asp-for="@Model.SupTitle">
                    <span asp-validation-for="@Model.SupTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Icon">Icon</label>
                    <input class="form-control" asp-for="@Model.Icon">
                    <span asp-validation-for="@Model.Icon" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.CretedDate">CreatedDate</label>
                    <input class="form-control" asp-for="@Model.CretedDate">
                    <span asp-validation-for="@Model.CretedDate" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
                <button type="submit" class="btn btn-dark" asp-controller="Service" asp-action="Index">Back to List</button>

            </form>
        </div>
    </div>
</div>

BarnetPages(Services)/BarnetPages/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>  Welcome  </h1>